BugOverload. Страница коллекции, страница персоны
VK-BMSTU-QA/homework-3-spring-2023 pull request #4
Opened 2023-04-17 17:57 UTC by Andeo1812

2023-05-07 14:39 UTC, lonkidely requested changes

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +4. Убедиться, что произошел редирект на страницу https://movie-gate.online/film/19/
Тогда уж не на любой фильм, урл будет другой
Ну и проверять тогда лучше по другому

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +5. Убедиться, что произошел редирект на страницу https://movie-gate.online/film/6/
аналогично, по урлу не проверяем

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +3. Нажать на красную урну в правом верхнем углу, который по наведению показывается
мб есть смысл убрать тест, автотестом не покроешь скорее всего

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +2. Найти желтую кнопнку в правом верхнем углу
кнопку

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +5. Убедиться, что произошел редирект на страницу https://movie-gate.online/film/6/
проверка на урл не ок

2023-05-07 14:39 UTC, lonkidely commented on BugOverload-Alexander-Anofrikov.md
> +5. Убедиться, что произошел редирект на страницу https://movie-gate.online/user/202/
снова

2023-05-07 16:43 UTC, Ivan-Bir approved these changes

2023-05-07 16:43 UTC, Ivan-Bir commented
Аппрув

2023-05-07 16:49 UTC, Andeo1812 commented on BugOverload-Alexander-Anofrikov.md
> +2. Найти желтую кнопнку в правом верхнем углу
+

2023-05-07 16:49 UTC, Andeo1812 commented on BugOverload-Alexander-Anofrikov.md
> +3. Нажать на красную урну в правом верхнем углу, который по наведению показывается
+

2023-05-07 16:54 UTC, lonkidely approved these changes

2023-05-07 17:11 UTC, Mike5535 approved these changes

2023-05-09 10:49 UTC, alexey-ershkov requested changes
Приветы, накинул комментов, довольно мало протестировано, возьми еще один блок сайта для тестов

2023-05-09 10:49 UTC, alexey-ershkov commented on .idea/.gitignore
.idea файлы надо удалить

2023-05-09 10:49 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +### Кейсы без авторизации
Лайк за разделение, давай еще добавим креды от тестового пользователя

2023-05-09 10:49 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +1. Перейти на страницу личной коллекции
Кажется тут нужно еще дописать дополнительно подготовку к тесту, чтобы добавить изначально в коллекцию фильм, а после теста вернуть в исходное состояние

2023-05-09 10:49 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +1. Перейти на страницу личной коллекции
Подготовка кстати может быть вынесена позже в отдельную функцию ибо у тебя много где фигурирует работа с личной коллекцией

2023-05-09 10:49 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +1. Перейти на страницу личной коллекции
тоже кейс с подготовкой, плюс кажется нужно переходить на страницу публичной коллекции

2023-05-09 10:49 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +#### Публичные личные коллекции содержат фильмы
Не нашел кейсов про добавление/изменение/удаление из коллекции, обработку ошибок и пр

2023-05-09 15:26 UTC, alexey-ershkov requested changes

2023-05-09 15:26 UTC, alexey-ershkov commented on BugOverload-Alexander-Anofrikov.md
> +#### Возможность удалить фильм в коллекцию
удалить фильм в коллекцию??)

2023-05-09 15:37 UTC, alexey-ershkov approved these changes
Аппрув

2023-05-09 15:37 UTC, alexey-ershkov approved these changes
Аппрув

2024-07-29 09:10 UTC, closed without merging