VDonate. Лайки, Комментарии, Авторские подписки
VK-BMSTU-QA/homework-3-spring-2023 pull request #5
Opened 2023-04-17 21:54 UTC by themilchenko

2023-04-18 07:58 UTC, george007361 requested changes

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +6. Комментарии к постам. При повторном нажатии комментарии скрываются;
Повторном нажатии на что?

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +12. Создание авторской подписки. Модальное окно закрывается при нажатии крестика или кнопки *Отменить* в окне;
Разбить на 2 кейса

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +13. Создание авторской подписки. Заголовок валидируется при соблюдении определенных требований;
Что за требования? Конкретные проверки нужно указать

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +14. Создание авторской подписки. Стоимость валидируется при соблюдении определенных требований;
Аналогично

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +17. Изменение/удаление авторской подписки. Возможность поменять поменять любое поле подписки;
поменять поменять

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +15. Создание авторской подписки. Текст валидируется при количестве символов больше 1 и меньше 128;
Разбить на 2 кейса

2023-04-18 07:58 UTC, george007361 commented on vdonate-milchenko-ivan.md
> +18. Изменение/удаление авторской подписки. Поведение при валидации идентично созданию подписки;
Тоже расписать

2023-04-18 21:34 UTC, themilchenko commented on vdonate-milchenko-ivan.md
> +15. Создание авторской подписки. Текст валидируется при количестве символов больше 1 и меньше 128;
Не понял, а для чего?

2023-04-19 09:12 UTC, george007361 approved these changes

2023-04-21 14:14 UTC, leonard-pak approved these changes

2023-04-21 16:28 UTC, zeronethunter approved these changes

2023-05-10 12:06 UTC, mistergahan requested changes

2023-05-10 12:06 UTC, mistergahan commented on vdonate-milchenko-ivan.md
> +
уберите лишнюю строку

2023-05-10 12:06 UTC, mistergahan commented on vdonate-milchenko-ivan.md
> +1. Лайки к постам. Нажатие на кнопку *лайка* серого цвета **мгновенно** увеличивает суммарное число на единицу;
а мы можем проверить мгновенность?

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +2. При повторном нажатии на кнопку *комментариев* они скрываются;
Кто они?

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +4. Возможность отправить комментарий с помощью сочетания клавиш *Shift + Enter*;
Действие - результат действия. как в пункте 3

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +5. Ошибка при попытке отправить пустой комментарий;
то же самое. что за ошибка?

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +7. Комментраий удаляется при нажатии автором комментария на крестик рядом с ним.
Действие - результат действия

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +3. При нажатии на кнопку *Отправить* комментарий успешно оставляется под постом;
а увеличение числа?

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +## Чек-лист
Во всех пунктах. Кмк надо указывать в каком контексте они проверяются. например, при тестировании комментариев надо указать, что при этом открыт блок комментариев у поста

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +6. При отсутствии картинки подписка успешно создается.
При отсутствии звучит странно. Но надо проверить загрузку картинки

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +6. Подписка успешно удаляеся при нажатии на кнопку *Удалить* в модальном окне.
Действие - результат действия

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +5. При неправильном заполнении форм после нажатия на кнопку *Создать* появляются следующие ошибки:
А что происходит с формой при этом? Ошибки - это уведомления?

2023-05-14 21:11 UTC, leonard-pak commented on vdonate-milchenko-ivan.md
> +5. При неправильном заполнении форм после нажатия на кнопку *Создать* появляются следующие ошибки:
А что происходит с формой при этом? Ошибки - это уведомления?

2023-05-15 13:25 UTC, leonard-pak commented
аппрув

2023-05-15 13:52 UTC, george007361 commented
Аппрув

2023-05-15 16:04 UTC, zeronethunter commented
Аппрув

2023-05-20 08:29 UTC, nikitarub commented
Все хорошо.

Есть вопросик на задуматься (при условии, что подписка на автора списывается ежемесячно): если автор удаляет подписку, что происходит с оплатами у подписчиков? Понятно дело, что это скорее всего не ваш сценарий, потому что ничего про ежемесячное списание средств вы не говорили, однако если такая фича появляется – надо это тоже учитывать.

2024-08-26 11:55 UTC, closed without merging