VDonate: Редактирование профиля, Popup уведомления
VK-BMSTU-QA/homework-3-spring-2023 pull request #6
Opened 2023-04-18 16:38 UTC by zeronethunter

2023-04-18 21:23 UTC, themilchenko requested changes
Надо немного поправить.

2023-04-18 21:23 UTC, themilchenko commented on VDonate-Albert-Kashapov.md
> +3. Редактирование профиля. Форма закрывается крестиком
Возможно, лучше написать `форма закрывается при нажатии на крестик`.

2023-04-18 21:23 UTC, themilchenko commented on VDonate-Albert-Kashapov.md
> +14. Редактирование профиля. Ошибка при запрещенных символах в никнейме (все, кроме латиницы, кириллицы, чисел, нижнего
Я бы добавил слово `наличии` между "при" и "запрещенных символов"

2023-04-18 21:23 UTC, themilchenko commented on VDonate-Albert-Kashapov.md
> +16. Редактирование профиля. Ошибка при неверном повторе пароля
Не совсем ясно, что значит "неверный повтор пароля". Понимаю, что это, скорее всего, несовпадение полей пароля и его подтверждения, но лучше расписать более подробно этот пункт.

2023-04-18 21:23 UTC, themilchenko commented on VDonate-Albert-Kashapov.md
> +15. Редактирование профиля. Ошибка при неверном пароле
Тут же имеется ввиду ошибка непраильного ввода по причине несоблюдения требований к полю ввода? Надо уточнить это.

2023-04-21 16:32 UTC, themilchenko approved these changes

2023-04-21 18:16 UTC, leonard-pak approved these changes

2023-04-22 07:18 UTC, george007361 approved these changes

2023-05-10 12:07 UTC, mistergahan approved these changes

2023-05-15 06:24 UTC, leonard-pak commented on VDonate-Albert-Kashapov.md
> +1. При загрузке большого аватара возникает ошибка
Что значит большой?

2023-05-15 06:24 UTC, leonard-pak commented on VDonate-Albert-Kashapov.md
> +3. При нажатии на кнопку "Вывести деньги" открывается форма с выбором способа вывода
при ненулевом балансе

2023-05-15 08:03 UTC, george007361 commented
Аппрув, дополнить нечем)

2023-05-15 13:26 UTC, leonard-pak commented
аппрув

2023-05-15 13:52 UTC, george007361 commented
Аппрув

2023-05-15 17:26 UTC, themilchenko commented
Аппрув

2023-05-20 08:41 UTC, nikitarub commented
Хорошо, что прописали краевые случаи, про минимальную и максимальную сумму вывода средств. Не очень понятно по тексту можно выводить только все сразу или определенную сумму (из-за чего, кстати, есть бага: если только разовое списание целиком, а на балансе накопилось больше 10к – вывести деньги не получится). 

P.S. По этому чеклисту создается ощущение, что подписка всё таки снимается ежемесячно – в чем я не уверен))

2024-03-14 17:17 UTC, closed without merging